### ISSUE TITLE
🐛 пропадает крестик, сжимается контент окна,слова из разных тегов слипаются,валидация 

### ISSUE THREAD

**Issue by Sh1mpi** [mospolytech-finapp/web#11]
# Описание проблемы
1. В окне "Связаться с нами" на телефонах с шириной экрана 320px пропадает крестик.
2. При нажатии на кнопку "Копировать" крестик пропадает, а другая кнопка "Копировать" сжимается (также на устройствах с шириной экрана 320px).
3. Текст валидации и "Забыли пароль" выглядят слитно, то же самое с "Нужна учетная запись" и "Связаться с нами", а также с "Уже зарегистрированы?" и "Связаться с нами".
4. В сообщении о валидации при регистрации не указано, что минимальная длина пароля - 8 символов.

## Воспроизведение проблемы
1. Крестик:
   1. Скачать [мобильный симулятор](https://chrome.google.com/webstore/detail/mobile-simulator-responsi/ckejmhbmlajgoklhgbapkiccekfoccmk?hl=ru).
   2. Открыть на iPhone 5 или на iPhone SE.
   3. Нажать "Связаться с нами".
   4. Обнаружить ошибку.
2. Сжимание:
   1. Скачать [мобильный симулятор](https://chrome.google.com/webstore/detail/mobile-simulator-responsi/ckejmhbmlajgoklhgbapkiccekfoccmk?hl=ru).
   2. Открыть на iPhone 5 или на iPhone SE.
   3. Нажать "Связаться с нами".
   4. Нажать на кнопку "Копировать".
   5. Обнаружить ошибку.
3. Слитный текст:
   1. Написать что-либо, не соответствующее валидации, в инпуты.
      1.1. Обнаружить ошибку.
   2. Нажать "Уже зарегистрированы?".
      2.1. Обнаружить ошибку.
   3. Открыть сайт.
      3.1. Обнаружить ошибку.
4. Валидация:
   1. Зайти в форму регистрации.
   2. Написать неподходящий пароль.
   3. Обнаружить ошибку.

## Ожидаемое поведение
1. Крестик должен присутствовать.
2. Не должно быть сжатия.
3. Текст должен переноситься на разные строки.
4. В сообщении о валидации при регистрации должно быть указано, что минимальная длина пароля - 8 символов.

## Фактическое поведение
На скриншотах ниже все видно.

## Компьютерная версия
- ОС: windows 11
- Браузер: yandex
- Версия: 23.3.1.896

**📷Скриншоты/видео**
1) ![image](https://user-images.githubusercontent.com/59705273/232341152-28b1b956-5506-4ca6-85a5-eee72c451afb.png)
2) ![2023-04-16_22-49-17](https://user-images.githubusercontent.com/59705273/232341166-5d4ef206-47ec-45f0-9712-377dae83284f.png)
3) ![2023-04-16_22-53-46](https://user-images.githubusercontent.com/59705273/232341180-45eec8d0-1589-438d-bb8c-55697e858bd5.png)
![2023-04-16_22-50-53](https://user-images.githubusercontent.com/59705273/232341187-67c69fcb-48a9-4eb7-9b60-2c2437b6491e.png)
![2023-04-16_22-50-45](https://user-images.githubusercontent.com/59705273/232341193-0555d8e1-bef4-4cde-932d-a1cd91f1c91a.png)
4) ![2023-04-16_23-07-59](https://user-images.githubusercontent.com/59705273/232341207-d95a3636-ce89-4b41-abe1-35a8afc0e045.png)

***📌Версия проекта***
0.0.1
***🔥Критичность***
не особо критично

**Comment by DimDimich-creator** [comment]
Поправь текст невозможно читать

**Comment by dangannn** [comment]
исправлено
