### ISSUE TITLE
🐛 Не открывается сайт в браузере

### ISSUE THREAD

**Issue by facexterm321** [mospolytech-finapp/web#12]
## 🚨Описание проблемы

1. В браузере Mozilla Firefox при открытии сайта по ссылке просто белый экран.

## 🔍Воспроизведение проблемы

1. Открыть браузер Mozilla FireFox
2. вставить ссылку (https://web-zeta-roan.vercel.app/auth) в адресной строке браузера.
3. обнаружить белый экран.

## 👀Ожидаемое поведение

1. Должна появится страница авторизации.

## 💥Фактическое поведение

Белый экран на странице (на скриншотах ниже).

## 💻Компьютерная версий

OC: Windows 10
браузер: Mozilla Firefox
версия: 69.0(32-битный)

## 📷Скриншоты/видео

![image](https://user-images.githubusercontent.com/131003708/232517366-e13a68ff-6991-437f-9663-1dddb102dfbe.png)

![image](https://user-images.githubusercontent.com/131003708/232518088-c5cf1f5b-ca8e-44e3-a306-faeb172b447f.png)

***📌Версия проекта*** 0.0.1
***🔥Критичность*** не особо критично

**Comment by DimDimich-creator** [comment]
а в других браузерах работает?
