### ISSUE TITLE
🐛 Две кнопки для отображения видимости пароля 

### ISSUE THREAD

**Issue by akarui-shi** [mospolytech-finapp/web#14]
## 🚨Описание проблемы

В браузере Microsoft Edge при вводе пароля в окнах регистрации и авторизации появляются два кликабельных значка для настройки отображения пароля

## 🔍Воспроизведение проблемы

1.  Ввела пароль в строке для ввода пароля в окнах авторизации и регистрации

## 👀Ожидаемое поведение

При вводе пароля отображается единственная кнопка для изменения видимости пароля, которая функционирует корректно

## 💥Фактическое поведение

При вводе пароля появляются два значки для настройки отображения пароля, оба функционируют корректно. При нажатии на правый значок левый пропадает

## 💻Компьютерная версия

- ОС: Windows 11
- Браузер: Microsoft Edge
- Версия: 112.0.1722.48 (Официальная сборка) (64-разрядная версия)

## 📷Скриншоты/видео

![2023-04-17_20-10-10](https://user-images.githubusercontent.com/125154747/232568996-7036e62e-3671-4001-8e99-abbe8662d728.png)

![2023-04-17_20-11-37](https://user-images.githubusercontent.com/125154747/232569037-f661ad61-086a-484d-a454-3df85721d834.png)

***📌Версия проекта***
0.0.1

***🔥Критичность***
Не особо критично

**Comment by DimDimich-creator** [comment]
решение:
```css
input::-ms-reveal,
input::-ms-clear {
        display: none;
      }
```

**Comment by TmP440** [comment]
Аналогичная ситуация на:
ОС: Windows 10 Pro
Браузер: Microsoft Edge
Версия: 112.0.1722.48 (Официальная сборка) (64-разрядная версия)
