### ISSUE TITLE
🐛При нажатии на "Связаться с нами" поля становятся красными

### ISSUE THREAD

**Issue by sergey030902** [mospolytech-finapp/web#16]
## 🚨Описание проблемы

Если поля не заполнены, то при нажатии на "Связаться с нами" они становятся красными

## 🔍Воспроизведение проблемы

Без заполнения полей при входе и регистрации нажал на "Связаться с нами"

## 👀Ожидаемое поведение

Цвет полей не должен меняться

## 💥Фактическое поведение

Цвет полей изменился на красный

## 💻Компьютерная версий

- ОС: Windows 11
- Браузер: Mozilla Firefox
- Версия: 112.0.1

## 📷Скриншоты/видео

![1](https://user-images.githubusercontent.com/84626037/232582361-911018ce-ba8d-4953-8dc9-2f3c4fa25058.png)
![2](https://user-images.githubusercontent.com/84626037/232582408-55f13a1f-b647-4b01-ab4e-163918bcc0cf.png)
![3](https://user-images.githubusercontent.com/84626037/232582436-9cb8cae0-cb68-4c77-a262-62c569e54371.png)
![4](https://user-images.githubusercontent.com/84626037/232582454-49c7bb88-a229-4371-baf4-72ad8094d33a.png)

***📌Версия проекта***
0.0.1
***🔥Критичность***
Не особо критично

**Comment by dangannn** [comment]
пофиксил валидацию при открытии модалки
