### ISSUE TITLE
🐛 Слово "Вход" съезжает

### ISSUE THREAD

**Issue by sergey030902** [mospolytech-finapp/web#18]
## 🚨Описание проблемы

При открытии формы входа слово "Вход" иногда съезжает

## 🔍Воспроизведение проблемы

Перейти на https://web-zeta-roan.vercel.app/auth
## 👀Ожидаемое поведение

Слово "Вход" должно находиться на правильном месте

## 💥Фактическое поведение

Слово "Вход" съезжает

## 📱Мобильная версия:

- Устройство: iPhone 11
- ОС: iOS 16.4.1
- Браузер: Safari

## 📷Скриншоты/видео

![IMG_4128](https://user-images.githubusercontent.com/84626037/232589148-2e520878-e8b1-4409-b990-8d0919ed683f.PNG)

***📌Версия проекта***
0.0.1
***🔥Критичность***
Не особо критично

**Comment by dangannn** [comment]
пофиксилось

**Comment by dangannn** [comment]
такая ошибка не возникает
