### ISSUE TITLE
🐛 Суженная форма регистрации и входа при первичном открытии или обновлении страницы одной из форм

### ISSUE THREAD

**Issue by TmP440** [mospolytech-finapp/web#22]
## 🚨Описание проблемы

При первом и повторном открытии форм регистрации и входа формы узкие. При нажатии на "Связаться с нами" в любой из форм или при попытке ввести логин в форме Входа формы растягиваются.

## 🔍Воспроизведение проблемы

[Опишите шаги, которые нужно предпринять, чтобы воспроизвести проблему]
1. Перейти на https://web-zeta-roan.vercel.app/register или на https://web-zeta-roan.vercel.app/auth
2. Нажать "Связаться с нами" или ввести логин на https://web-zeta-roan.vercel.app/auth
3. Обнаружить ошибку

## 👀Ожидаемое поведение

Ожидалось, что формы не будут менять свою ширину

## 💥Фактическое поведение

По факту формы меняют свою ширину

## 💻Компьютерная версий

- ОС: Windows 10 Pro
- Браузер: Yandex
- Версия: 23.3.2.806 (64-bit)

## 📝Дополнительная информация

В форме регистрации изменил масштаб окна, но фактический размер формы в панели разработчика не изменился (проверил)

## 📷Скриншоты/видео

- Первичное или повторное открытие форм:
![image](https://user-images.githubusercontent.com/63639938/232876248-8c4e84bd-0437-405a-a4b4-4b376c9088d4.png)
![image](https://user-images.githubusercontent.com/63639938/232877052-ddce1981-ee8b-4406-832b-06f483a895ed.png)
- После нажатия на кнопку "Связаться с нами" или ввода логина на https://web-zeta-roan.vercel.app/auth
![image](https://user-images.githubusercontent.com/63639938/232877915-ca9e0bd1-4996-44c3-a29a-bacc26e722a0.png)
![image](https://user-images.githubusercontent.com/63639938/232878063-2f94faef-70cf-4539-b5e3-f154d5a27abd.png)

***📌Версия проекта***
0.0.1
***🔥Критичность***
Незначительная

**Comment by TmP440** [comment]
Аналогичная проблема на:
- ОС: Windows 10 Pro
- Браузер: Google Chrome
- Версия: 111.0.5563.149 (Официальная сборка), (64 бит)

**Comment by dangannn** [comment]
исправлено
