### ISSUE TITLE
🐛 Не работают фильтры по категориям

### ISSUE THREAD

**Issue by nonemoff** [mospolytech-finapp/web#75]
## 🚨Описание проблемы

Не работают фильтры по категориям

## 🔍Воспроизведение проблемы

1. Зашел на страницу всех транзакций
2. Создал транзакцию с категорией "продукты"
3. Создал транзакцию с другой категорией
4. Выбрал в фильтрах категорию "продукты"

## 👀Ожидаемое поведение

Отобразится транзакция с категорией "продукты", а остальне исчезнут

## 💥Фактическое поведение

Не отобразилось ни одной транзакции

## 💻Компьютерная версий

- ОС: Windows 10
- Браузер: Google Chrome
- Версия: Chrome Версия 113.0.5672.94 (Официальная сборка), (64 бит)

## 📱Мобильная версия:

не проверял

## 📷Скриншоты/видео
![image](https://github.com/mospolytech-finapp/web/assets/57914248/68ac2403-c3b7-480a-a7c8-d5dd39d3a680)

***📌Версия проекта***
***🔥Критичность***
высокая

**Comment by f1xgun** [comment]
предоставь логи запросов на бэк, либо данные от аккаунта, можно в лс tg: f1xgun

**Comment by f1xgun** [comment]
Исправлено #77
